name: Dependabot PR Auto-Merge dockerfile

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'Dockerfile'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
            app-id: ${{ vars.DEPENDABOT_APP_ID }}
            private-key: ${{ secrets.DEPENDABOT_APP_PRIVATE_KEY }}

      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}